apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: disentangle
data:
  cluster_name: "disentangle-local"
  arch: "amd64"
  infra: "local"
  nodes: "3"
  resources: "small"
  cpu_limit: "250m"
  memory_limit: "256Mi"
  cpu_request: "50m"
  memory_request: "64Mi"
  pow_difficulty: "4"
  nebula_mode: "node"
  nebula_prefix: "10.42.2"
