---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: disentangle
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-disentangle-p2p
  namespace: disentangle
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: disentangle
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: disentangle
      ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: disentangle
      ports:
        - protocol: TCP
          port: 9000
    - to: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nebula-udp
  namespace: disentangle
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: nebula
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: UDP
          port: 4242
  egress:
    - ports:
        - protocol: UDP
          port: 4242
